### PR TITLE
Feature sync gfw

### PR DESCRIPTION
**Pull request by karenmiko**
Hi @RandyTrigg,
Hopefully this will merge all my sync-related code into main. Let me know if you have any questions or concerns. Thanks!

### CODE REVIEW

**Comment by karenmiko** [comment]
Looks like there's one conflict with aliases.sh - just a few additional lines. But I'm not sure how to resolve...

**Comment by RandyTrigg** [comment]
Go for it, Karen! I see that your only conflict is aliases.sh - I probably added something. Hopefully you can just accept my version?

**Comment by karenmiko** [comment]
Hi Randy,

Sorry, I can't figure out how to resolve the conflict. It's just for the
following lines:

[image: image.png]

It says you can use the web editor to resolve the conflict, but I can't
figure out what to do... have you done this before?

Karen

**Comment by RandyTrigg** [comment]
You did it. Yay!

[Global Fund for Women]<http://www.globalfundforwomen.org/>
Randy Trigg | Director of Information Management
Global Fund for Women<http://www.globalfundforwomen.org>
800 Market Street, 7th Floor | San Francisco, CA 94102

direct
+1.415.248.4836
fax
+1.415.248.4801
pronouns: he/his

website<http://www.globalfundforwomen.org> | vCard<https://dynasend.com/signatures/vcard/rtrigg-at-globalfundforwomen.org.vcf> | ***@***.***,-122.406616,15z/data=!4m2!3m1!1s0x80858086024410a9:0xa6b9836637f4ccb4?hl=en> | ***@***.***>
[Donate]<https://join.globalfundforwomen.org/a/donate>[Facebook]<https://www.facebook.com/GlobalFundforWomen>[Twitter]<https://www.twitter.com/GlobalFundWomen>[LinkedIn]<https://www.linkedin.com/pub/randy-trigg/a/192/292>[Pinterest]<http://pinterest.com/globalfundwomen>
Confidentiality Note: This email may contain confidential and/or private information. If you received this email in error please delete and notify sender.

**Pull request merged**
